In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [5]:
np.random.randint(1,2,size=3)

array([1, 1, 1])

In [11]:
randarr = np.arange(25)

In [12]:
randarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
randarr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
print(randarr.max())
print(randarr.min())

24
0


In [19]:
randarr.argmax()

24

In [21]:
randarr.dtype.type

numpy.int32

In [22]:
randarr[0:5]=100

In [23]:
randarr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [25]:
array2d = np.array([[5,10,15],[20,25,30],[35,40,45],[50,55,60],])

In [26]:
array2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [30]:
array2d[1][-1]

30